//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedZoneCatsVideoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat()
        {
            this.Video_Cat_Junction = new HashSet<Video_Cat_Junction>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string breed { get; set; }
        public string sex { get; set; }
        public string age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video_Cat_Junction> Video_Cat_Junction { get; set; }
    }
}
