//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedZoneCatsVideoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_Cat_Junction
    {
        public int video_cat_id { get; set; }
        public int video_id { get; set; }
        public int cat_id { get; set; }
    
        public virtual Cat Cat { get; set; }
        public virtual Video Video { get; set; }
    }
}
